os: linux
services: docker
language: minimal
install: skip
stages:
  - lint
  - test
env:
  - CMD="docker run --rm -itv $(pwd):/go/src/github.com/filebrowser/caddy -w /go/src/github.com/filebrowser/caddy filebrowser/dev sh -c"
jobs:
  include:
  - stage: lint
    script: $CMD "go get -v ./... && golangci-lint run -v"
  - stage: test
    script: $CMD "$(cat ./build.sh)"
